image:
    file: .gitpod.Dockerfile
tasks:
  - init: |
      sudo apt-get update && \
      sudo apt-get install -y \
      tesseract-ocr \
      libtesseract-dev \
      libleptonica-dev \
      python3-pip \
      python3-dev \
      && sudo apt-get clean
      pip3 install --upgrade pip setuptools wheel && pip3 install -r requirements.txt
    command: python main.py